### ISSUE TITLE
HOW TO SETUP WALLET 

### ISSUE THREAD

**Issue by lueejack** [TkEriot/Minesweeper#1]
DEPOSTI OR WITHDRWAL BITCOIN ADDRESS NOT SHOW

**Comment by xSplit** [comment]
Setup bitcoin daemon and change config in core.php, example:
`$server_btc = 'http://username:password@'.$server_ip.':port/';`

To launch bitcoin gui as daemon:
`C:\Bitcoin\bitcoin-qt.exe -server -rpcuser=USERNAME -rpcpassword=PASSWORD -rpcport=PORT -rpcallowip=0.0.0.0/0`

Assuming you configured correctly the rest of the things
